### PR TITLE
Add support for running test262 suite against JS-Interpreter

### PR DESCRIPTION
**Pull request by pcardune**
I've spent some time working on running the "Official ECMAScript Conformance Test Suite" (https://github.com/tc39/test262) against JS-Interpreter to get an idea of what works and what doesn't and track changes over time.

I wanted to see if you were interested in having that work merged into this repository. Here are some specific things I implemented (of which you may only be interested in a subset):
- an npm package (currently under the @code-dot-org namespace) that other projects can depend on for "official" releases.
- circleci integration to automatically run the entire test262 test suite on every commit
- a test runner called js-interpreter-tyrant (https://github.com/code-dot-org/js-interpreter-tyrant) that can run many tests in parallel across multiple circle hosts, aggregate results into a single file, and compare test results between multiple test runs to show what got fixed and what was broken with any given change.

Here is a summary of the test results for the latest commit to this repo:
Results:
  es5: 12539/22318 (56%) passed
  es6: 1973/19926 (9%) passed
  es: 807/3927 (20%) passed
  other: 160/781 (20%) passed

I don't expect this pull request to get merged as is, but if comprehensive testing is something you are interested in having, I'd be happy to work on a pull request with just the minimal set of changes to make that happen.

### CODE REVIEW

**Comment by pcardune** [comment]
I accidentally opened this pull request in error and then closed it, but now I've reopened it with appropriate comments as to what I'm trying to do here 😄. I would greatly appreciate if you could take a look and let me know what you think.

**Comment by joshlory** [comment]
It looks like this PR now contains additional changes beyond the test262 suite.  Worth rebasing into a smaller set of changes to prepare this for possible merge?

**Comment by joshlory** [comment]
@NeilFraser is this approach to test coverage something you'd be open to?  If not, what sort of test coverage should we pursue?  Thank you!

**Comment by NeilFraser** [comment]
Thumbs up for using test262 for unit testing.  Don't have an opinion regarding which framework.

However, adding 'require()' and 'module' in interpreter.js is a no-go since that destroys the ability to run the interpreter in a browser.

**Comment by NeilFraser** [comment]
I should also point out that test262 is a bit weird in what it tests.  It is utterly obsessed with 0, -0, NaN, Infinity, and the non-deletability of function.length.  But more often than not it doesn't actually test the function with a normal input.

For example, Math.sin is tested with these inputs:

-   NaN
-   Infinity
-   -Infinity
-   0
-   -0

But there are no tests for PI, PI/2, -PI/4, etc.  I'm not very excited about tests where Math.sin and Math.tan could be swapped and the tests still pass.

**Comment by pcardune** [comment]
> However, adding 'require()' and 'module' in interpreter.js is a no-go since that destroys the ability to run the interpreter in a browser.

I see two options for addressing this:

1. It looks like you already have a build process in place somewhere for generating the compressed bundle. Converting the `module.export` and `require` statements to something web compatible (AMD, CommonJS, globals, etc) should be easy to add to that build process, using webpack, browserify, or any of a number of build tools.

2. We can just bake in the small amount of code to support multiple environments right in `interpreter.js` using the [UMD pattern](https://github.com/umdjs/umd)

Do you have a preference for one vs. the other?

> It is utterly obsessed with 0, -0, NaN, Infinity, and the non-deletability of function.length.

Yep, definitely lots of obscure edge cases in the test262 suite. I think it would be quite reasonable for us to add our own collection of tests for things we particularly care about. In particular, I think testing the public javascript interface to the interpreter would be pretty useful: things like creating various types of interpreter objects.

As for next steps, what would you like to see in a PR that could actually get merged? And what do you think about the npm package stuff?

**Comment by NeilFraser** [comment]
Hmm.  Option 1 is poor since the primary advantage of a scripting language is that one doesn't have a compile cycle while developing it (although there may be one during release).  Option 2 is poor since we are adding global-scoped code to everyone that they don't need.

Is there a test framework that doesn't dictate how one writes code?  Tests should support the code, the code shouldn't support the tests.

**Comment by pcardune** [comment]
> Is there a test framework that doesn't dictate how one writes code? Tests should support the code, the code shouldn't support the tests.

The `module.exports` stuff is not needed for the tests, and can be easily removed. It's just to make the npm package work like the majority of other npm packages which don't write to globals. If you don't have any interest in there being an npm package, then module.exports/require is a non-issue.

**Comment by cpcallen** [comment]
@NeilFraser: do we want this closed?

**Pull request closed without merging**
