### PR TITLE
nodejs support

### PR DESCRIPTION
**Pull request by EasyHard**
Add nodejs support. It can be used like

```
var code = fs.readFileSync('./code/fib.js');
var Interpreter = require('./interpreter');
var myInterpreter = new Interpreter(code);
myInterpreter.run();
console.log('value:', myInterpreter.value.data);
```

and then
`node run.js`
 where `run.js` is as above.

### CODE REVIEW

**Comment by liebig** [comment]
:+1:

**Comment by Lokidottir** [comment]
+1

**Comment by Dinuka2013513** [comment]
Hi @EasyHard  @liebig @Lokidottir 

Does this have following functionalities..
function.bind
array.filter
array.map

I checked, But, it didn't work.

**Comment by NeilFraser** [comment]
A demo of node is now included in the repo: https://neil.fraser.name/software/JS-Interpreter/demos/node.js

**Pull request closed without merging**
