### PR TITLE
Fix mistake in documentation

### PR DESCRIPTION
**Pull request by carloslfu**
JavaScript is single-threaded as [MDN explains](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop)

### CODE REVIEW

**Comment by NeilFraser** [comment]
The intent was to convey the fact that the JS Interpreter could be used to create a multi-threaded environment.  Indeed, that was one of the design requirements.  Start by creating several interpreters, then loop through each interpreter, making one step at a time.  This is the same way that multi-threaded operating systems work, despite a single-core processor being single-threaded.

An example of the JS Interpreter being used for a multi-threaded task are the Ducks in Blockly Games: https://blockly-games.appspot.com/pond-duck  Just press 'Run Program'.

**Comment by carloslfu** [comment]
The mistake regards in the fact that [JavaScript is inerently single-threaded](http://stackoverflow.com/a/39961) and the unique way to achive truly multi-threading is to use [Web Workers](https://developer.mozilla.org/es/docs/Web/API/Web_Workers_API). The technique JS-Interpreter uses allows programs to be concurrent in an elegant way, but without webworkers these programs are executed in the main thread and only a single core of the processor are used.

**Comment by RoboTeddy** [comment]
@carloslfu it's true that (in the browser), web workers are the only way to execute js in parallel. But, colloquially speaking, threads don't have to be executed in parallel in order to be called threads!

If you wrote a C program with threads and ran it on a single core computer, you'd still say that the program was multi-threaded.

**Comment by carloslfu** [comment]
@NeilFraser you are right, thanks for the explanation

**Pull request closed without merging**
