### PR TITLE
Set paused_=true before calling an asynchronous function

### PR DESCRIPTION
**Pull request by wastl-junior**
Needed when a synchronous native function is declared as asynchronous one.
Because then the callback will be called (paused_ will be reset to false) before paused_ was set to true.
In this case the execution of the interpreter will be stopped unexpectedly.
Because paused_ will be set to true after the execution of the native function.

### CODE REVIEW

**Comment by ferrao** [comment]
I was getting hit by this on a function which is async most of the time, but in some exceptional cases sync. Something like :

```
function mostlyAsync(cb) {
    if (exceptionalCase()) {
        cb();
        return
    }

    // generic case
    doSomethingAsync(cb);
} 
```

I really think this simple fix should be implemented @NeilFraser, any reason for not doing it?

**Comment by wastl-junior** [comment]
please merge this!

**Comment by NeilFraser** [comment]
Hi wastl-junior,

We are trying to transfer the JS Interpreter to Google's open source repo where it can be maintained better than in my personal repo. To do so we need you to sign Google's Contributor License Agreement.

📝 Please visit https://cla.developers.google.com/ to sign.

Thank you very much!

**Comment by NeilFraser** [comment]
Ping @wastl-junior for signing the Google CLA.  I know it's only swapping two lines, but lawyers...
https://cla.developers.google.com/

**Comment by wastl-junior** [comment]
really annoying ... i signed the CLA :wink:

**Pull request merged**
