### PR TITLE
fix infinite exceptions calling foo.bar() when foo is not defined

### PR DESCRIPTION
**Pull request by cpirich**
In our use of the interpreter, we've received feedback that calling foo.bar() when foo is not defined should fail, but not continue to fail in an infinite loop. (each step() call would get stuck in `stepCallExpression` and throw an exception repeatedly)

I've fixed this particular case by avoiding two places (in `stepIdentifier` and `stepCallExpression`) where state.value would be undefined after throwing an exception (setting to `this.UNDEFINED` is preferred). I also fixed part of the state machine within `stepCallExpression` such that state.arguments would be initialized prior to throwing an exception.

There may be other cases similar to this one that I did not fix. General changes to all callers of `getValueFromScope` could also be considered.

### CODE REVIEW

**Comment by cpirich** [comment]
This has been updated to include the case of calling a undefined function (example: `functionThatDoesntExist();`). That would also cause the state machine inside `stepCallExpression` to loop continuously after throwing an exception each time. I tested the two remaining callers that don't guard against this while calling `getValueFromScope` or `getValue` (which returns a result from `getValueFromScope`), which are `stepAssignmentExpression` and `stepUpdateExpression` and those fail to loop infinitely because they don't contain state machines that get confused after those calls fail with an exception.

**Comment by NeilFraser** [comment]
Can you clarify how to reproduce this?  Using the demo at https://neil.fraser.name/software/JS-Interpreter/ I've tried:

bar();

foo.bar();

var foo;
foo.bar();

All three throw the appropriate error and terminate in both step by step mode and run mode.

**Comment by cpirich** [comment]
We have a different scenario where we want to continue stepping/running even after hitting an exception. The student will be informed that a particular line of code caused a runtime error, but we want to continue to run the rest of their code.

The demo will stop running as soon as it hits an exception. In our scenario, we attempt to capture the runtime error in the `step()` call, and the continue calling `step()` again. For the scenario below, we want to indicate an error during the call to `foo.bar()` but still execute the `alert()` at the end. The good news is that this works in general, but there are a couple of cases where interpreter state would prevent the subsequent `step()` call from moving forward.

```
var foo;
foo.bar();
alert("finished");
```

**Comment by cpirich** [comment]
Hi Neil,

I signed the agreement. Sorry for the delay. Let me know if it didn't work for any reason.

Thanks,

Chris

**Comment by NeilFraser** [comment]
Confirmed on this end.  Thanks!

**Pull request merged**
