### PR TITLE
String search function, split with regex argument, and array sort function

### PR DESCRIPTION
**Pull request by ecampver**

### CODE REVIEW

**Comment by NeilFraser** [comment]
Very cool.  One problem though.  Single-stepping through this code causes a crash:
[1,2,3].sort(function(a,b){while(1){}});

**Comment by ecampver** [comment]
I tested it in both the interpreter and in JavaScript and they have the same behavior: the moment the execution reaches the while, the page stops responding due to the infinite loop. Isn't that the desired behavior?

**Comment by NeilFraser** [comment]
The purpose of the interpreter is to be able to execute untrusted 3rd party code without security issues.  while(1){} in the interpreter does not crash the browser, it just takes an infinite number of steps to complete.  The interpreter needs to be able to step through the sort function's code.

I don't think that the native sort function may be used here.  I think you need to write your own sort (bubble sort is fine for now, efficiency is not a concern).  But I could be wrong.

**Comment by ecampver** [comment]
I don't exactly get what you mean with "step through the sort function's code". Let's see, if we run `[1,2,3].sort(function(a,b){while(1){}});` in the example page, is it supposed to highlight `sort` in every step, or to step into the comparison function every time `sort` needs to compare two values, and then back to `sort` and in again and so on?

**Comment by NeilFraser** [comment]
In order to prevent infinite loops from crashing the browser, all non-atomic execution needs to be stepped.  Thus a sort would need to step all the way through the comparison function code every time the sort algorithm called it (which could be a lot of times for a single sort).

**Pull request merged**
