### PR TITLE
ADD: ToPrimitive and DefalutValue methods, to comply with ecma spec

### PR DESCRIPTION
**Pull request by futurist**
This PR is according to spec [9.1](http://www.ecma-international.org/ecma-262/5.1/#sec-9.1) and [8.12.8](http://www.ecma-international.org/ecma-262/5.1/#sec-8.12.8)

The `ToPrimitive` usage is just applied to `'+'` operator ([11.6.1](http://www.ecma-international.org/ecma-262/5.1/#sec-11.6.1)), and maybe enlarge the usage range (like `a>b`, `a<b` etc.) later if this PR been accepted.

Please review.

### CODE REVIEW

**Comment by NeilFraser** [comment]
Does 00ae335ecdaaff7d91f5d804fc5181a17198e547 fix the issues addressed in this PR?

**Comment by futurist** [comment]
The spec for addtion `+` said as below:

> 7. If Type(lprim) is String or Type(rprim) is String, then `ToString` first, otherwise `ToNumber` first.

So I think the logic of original code is right.

`lprim` and `rprim` is result from `ToPrimitive` function, this PR added this function.

**Comment by NeilFraser** [comment]
Indeed, the code in this PR looks correct.  But I'm trying to ascertain if there are any cases that aren't solved by the much simpler code in 00ae335ecdaaff7d91f5d804fc5181a17198e547 and af27a66b7e9e000c4a1d1a7d485e4bbbec2aad49.

Those two commits seem to have fixed all the cases I can think of.

**Comment by futurist** [comment]
These 2 commit I think is try to cast into it's `DefaultValue`, as a primitive value.

> When the [[DefaultValue]] internal method of O is called with hint String, the following steps are taken:
> 
> Let toString be the result of calling the [[Get]] internal method of object O with argument "toString".
> If IsCallable(toString) is true then,
> Let str be the result of calling the [[Call]] internal method of toString, with O as the this value and an empty argument list.
> If str is a primitive value, return str.
> Let valueOf be the result of calling the [[Get]] internal method of object O with argument "valueOf".
> If IsCallable(valueOf) is true then,
> Let val be the result of calling the [[Call]] internal method of valueOf, with O as the this value and an empty argument list.
> If val is a primitive value, return val.
> Throw a TypeError exception.
> 
> When the [[DefaultValue]] internal method of O is called with hint Number, the following steps are taken:
> 
> Let valueOf be the result of calling the [[Get]] internal method of object O with argument "valueOf".
> If IsCallable(valueOf) is true then,
> Let val be the result of calling the [[Call]] internal method of valueOf, with O as the this value and an empty argument list.
> If val is a primitive value, return val.
> Let toString be the result of calling the [[Get]] internal method of object O with argument "toString".
> If IsCallable(toString) is true then,
> Let str be the result of calling the [[Call]] internal method of toString, with O as the this value and an empty argument list.
> If str is a primitive value, return str.
> Throw a TypeError exception.

There's 2 condition: hint for string and hint for number, each with multiple steps.

So a simple `.data` and `.toString` cannot cover the situation, with this PR, you can try:

```js
alert([]+{})
```

It's `"[object Object]"` in all browsers, the result comply with standard too, since the steps:

1. [], {} both is not string type, so the hint is **Number**
2. [].data (valueOf) is `[]`, it's not primitive type, so give it another `toString`, result `""`
3. ({}).data (valueOf) is `{}`, it's not primitive type, so give it another `toString`, result `"[object Object]"`
4. both left and right is string type, do the addition with string concat.
5. `""+"[object Object]"` result is `"[object Object]"`

For the compare operations, the steps **1-3** is the same.

This PR try to pull step 1-3 into a function, and make it applied for any needed conditions, like `+,<,>,==` etc.

**Comment by NeilFraser** [comment]
`alert([]+{})` is correctly handled by 00ae335ecdaaff7d91f5d804fc5181a17198e547 in that in returns "[object]" (the difference between "[object]" and "[object Object]" is a matter of the object's toString function, which is an unrelated issue).

Can you provide a simple addition that 00ae335ecdaaff7d91f5d804fc5181a17198e547 handles incorrectly?

**Comment by futurist** [comment]
Yes, 00ae335 is more concise, since it's borrowed from the native JS `+` implementation, this line https://github.com/NeilFraser/JS-Interpreter/commit/00ae335ecdaaff7d91f5d804fc5181a17198e547#diff-966ad2ec9f775b3820dd37b4d36b650aR2618 will run the function `ToPrimitive` counterpart from native JS engine, that is, out of the sandbox. This PR try to put `ToPrimitive` into the sandbox.

It's depends on how to divide the boundary of the sandbox and native, although the result is indeed the same.

**Pull request closed without merging**
